// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

// (Generated Firebase options below)

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJDQ5ROTd44sEQHtVBvt48mFrqzNeWqQ',
    appId: '1:591673220052:android:cd06cda2aea5af05f9d441',
    messagingSenderId: '591673220052',
    projectId: 'retailflow-ai-fb-hosting66',
    storageBucket: 'retailflow-ai-fb-hosting66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyxi2abg-wb3ZSw9BzAKkNkfbnpZ6N55Y',
    appId: '1:591673220052:ios:4c8a50849c86a745f9d441',
    messagingSenderId: '591673220052',
    projectId: 'retailflow-ai-fb-hosting66',
    storageBucket: 'retailflow-ai-fb-hosting66.firebasestorage.app',
    iosBundleId: 'com.example.muraliFruitsMl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyxi2abg-wb3ZSw9BzAKkNkfbnpZ6N55Y',
    appId: '1:591673220052:ios:4c8a50849c86a745f9d441',
    messagingSenderId: '591673220052',
    projectId: 'retailflow-ai-fb-hosting66',
    storageBucket: 'retailflow-ai-fb-hosting66.firebasestorage.app',
    iosBundleId: 'com.example.muraliFruitsMl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5mYReH1VpZKnGk-TjGWLXZF2CimaazgY',
    appId: '1:591673220052:web:6c98cb115f9b4618f9d441',
    messagingSenderId: '591673220052',
    projectId: 'retailflow-ai-fb-hosting66',
    authDomain: 'retailflow-ai-fb-hosting66.firebaseapp.com',
    storageBucket: 'retailflow-ai-fb-hosting66.firebasestorage.app',
  );

}